### ISSUE TITLE
Why is path dropped?

### ISSUE THREAD

**Issue by ecdeveloper** [s0md3v/Corsy#27] opened 2020-08-19 16:59 UTC
I've been trying to run the script against URLs that look like `https://example.com/foo/bar`, and it looks like `/foo/bar` piece is being dropped, so we test only against the root domain - `https://example.com`. Any reason for doing that?

**Comment by not-duckie** [comment] 2020-08-19 17:22
hey, test my fork of the tool and see if the problem still persists

**Comment by ecdeveloper** [comment] 2020-08-19 18:41
I've actually fixed it locally by adding the parsed path to the url, but I was curious if it's a bug or intended behavior.

**Comment by s0md3v** [comment] 2020-08-21 04:02
It is intended behavior. Do you guys want me to "fix" it?

**Comment by ecdeveloper** [comment] 2020-08-21 06:24
Here's my thinking behind keeping the path. Sometimes various paths may have different CORS rules. More so, sometimes two different paths under the same hostname may point to different backends, so IMO it makes sense to scan all available paths.

**Comment by s0md3v** [comment] 2021-01-28 11:28
This issue has been fixed now.

**Closed by s0md3v** 2021-01-28 11:28 UTC
